# Q.1 Use numpy to generate array of 25 random numbers sampled from a standard normal distribution

In [1]:
import numpy as np
arr=np.random.normal(0,1,25)
print(arr)

[-0.25464445  0.08712712 -0.2456596   1.28284907  0.83975272 -0.50589149
  1.16632693  0.39547352  0.09355405 -1.15117449  0.36993888  0.39742269
 -0.10486757 -0.82552764 -0.06832648 -1.60327226  0.8514439  -1.24318175
  0.64272421  0.47160844  0.0408531  -0.49440583  0.61574383 -0.04989095
  0.82852012]


# Q.2 Create a random vector of size 30 and find the mean value.

In [2]:
import numpy as np
vect=np.random.random(30)
mean=vect.mean()
print(mean)

0.5644898642900885


# Q.3 Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.

In [3]:
import numpy as np 
arr=np.linspace(1,100,100)
arr=arr.reshape(10,10)
print(arr)


[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100.]]


# Q.4 Create a 10x10 array with random values and find the minimum and maximum values.

In [4]:
import numpy as np
arr=np.random.random((10,10))
mini=arr.min()
maxi=arr.max()
print('Minimum no in the array is {}\nMaximum no. in the array is {}'.format(mini,maxi))

Minimum no in the array is 0.026783686697130604
Maximum no. in the array is 0.9953652069489415


# Q.5 Find Dot product of two arrays

f = np.array([1,2])

g = np.array([4,5])

In [5]:
import numpy as np

f = np.array([1,2])

g = np.array([4,5])

prod=f.dot(g)
print(prod)

14


# Q.6 Concatenate following arrays along axis=0
x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])

In [6]:
x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])

conc=np.concatenate((x,y),axis=0)
print(conc)

[[1 2]
 [3 4]
 [5 6]]


# Q.7 How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

common=np.intersect1d(a,b)
print(common)


[2 4]


# Q.8 Sort the numpy array:

arr = np.array([10,5,8,4,7,2,3,1])

In [8]:
arr = np.array([10,5,8,4,7,2,3,1])

sort=np.sort(arr)

print(sort)

[ 1  2  3  4  5  7  8 10]
